name: Build Flet App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Install Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          sudo mkdir -p /usr/local/android-sdk/cmdline-tools
          sudo unzip cmdline-tools.zip -d /usr/local/android-sdk/cmdline-tools
          sudo mv /usr/local/android-sdk/cmdline-tools/cmdline-tools /usr/local/android-sdk/cmdline-tools/latest
          
          # Installer les outils nécessaires pour Android
          echo "export ANDROID_HOME=/usr/local/android-sdk" >> $GITHUB_ENV
          echo "export PATH=\$ANDROID_HOME/cmdline-tools/latest/bin:\$PATH" >> $GITHUB_ENV
          echo "export PATH=\$ANDROID_HOME/platform-tools:\$PATH" >> $GITHUB_ENV

      - name: Accept Licenses
        run: |
          yes | sdkmanager --licenses
          sdkmanager --update
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

      - name: Install dependencies
        run: pip install -r requirements.txt


